services:
  web:
    build: .
    command: runserver
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432 

  redis:
    image: redis:7
    ports:
      - "6379"

  celery:
    build: .
    command: celery
    depends_on:
      - db
      - redis
    env_file:
      - .env