# Generated by Django 5.1.4 on 2025-01-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crypto',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
