# Generated by Django 5.1.4 on 2025-01-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='historical_data',
            field=models.FileField(blank=True, null=True, upload_to='assets/historical_data/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='predicted_data',
            field=models.FileField(blank=True, null=True, upload_to='assets/predicted_data/'),
        ),
    ]
