# Generated by Django 5.1.4 on 2025-01-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_predicteddata_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicteddata',
            name='actual_price',
            field=models.FloatField(),
        ),
    ]
