# Generated by Django 5.1.4 on 2025-01-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_predicteddata_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='timeframe',
            field=models.CharField(choices=[('1day', '1 Day'), ('7day', '7 Days'), ('1month', '1 Month'), ('1year', '1 Year')], default='year', max_length=10),
            preserve_default=False,
        ),
    ]
