# Generated by Django 5.1.4 on 2025-01-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_historicaldata_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='timeframe',
            field=models.CharField(choices=[('day', '1 Day'), ('7day', '7 Days'), ('month', '1 Month'), ('year', '1 Year')], max_length=10),
        ),
    ]
