# Generated by Django 5.1.4 on 2025-01-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_historicaldata_timeframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predicteddata',
            name='actual_price',
        ),
        migrations.AddField(
            model_name='predicteddata',
            name='lower_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predicteddata',
            name='upper_bound',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
