# Generated by Django 5.1.4 on 2025-01-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_predicteddata_actual_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predicteddata',
            name='lower_bound',
        ),
        migrations.RemoveField(
            model_name='predicteddata',
            name='upper_bound',
        ),
        migrations.AddField(
            model_name='predicteddata',
            name='timeframe',
            field=models.CharField(choices=[('day', '1 Day'), ('week', '7 Days'), ('month', '1 Month'), ('year', '1 Year')], default='day', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predicteddata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
