# Generated by Django 5.1.4 on 2025-01-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_predicteddata_lower_bound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicteddata',
            name='confidence',
            field=models.FloatField(default=75.0),
            preserve_default=False,
        ),
    ]
