# Generated by Django 5.1.4 on 2025-01-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_predicteddata_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='historical_data',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='predicted_data',
        ),
        migrations.AddField(
            model_name='asset',
            name='change',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predicteddata',
            name='duration',
            field=models.PositiveBigIntegerField(default=7),
            preserve_default=False,
        ),
    ]
