# Generated by Django 5.1.4 on 2025-01-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_asset_historical_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicteddata',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
