# Generated by Django 5.1.4 on 2025-02-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_predicteddata_predicted_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicteddata',
            name='predicted_high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predicteddata',
            name='predicted_low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predicteddata',
            name='predicted_open_price',
            field=models.FloatField(),
        ),
    ]
