# Generated by Django 5.1.4 on 2025-02-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_predicteddata_predicted_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='change',
        ),
        migrations.AddField(
            model_name='asset',
            name='percent_change',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_change',
            field=models.FloatField(default=0),
        ),
    ]
