# Generated by Django 5.1.4 on 2025-02-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_asset_change_asset_percent_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='percent_change',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price_change',
            field=models.FloatField(),
        ),
    ]
