# Generated by Django 5.1.4 on 2025-02-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_asset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(default='asset_images/blank-product.jpg', upload_to='asset_images/'),
        ),
    ]
