# Generated by Django 5.1.7 on 2025-05-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_asset_close_price_alter_asset_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='percent_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price_change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
